// <auto-generated />
namespace DetroitEatz.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class ReplaceDetroitEats : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ReplaceDetroitEats));
        
        string IMigrationMetadata.Id
        {
            get { return "201508250202594_ReplaceDetroitEats"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
